#ifndef LDB_VERSION_H
#define LDB_VERSION_H

#define LIBDUSTBUNNY_VERSION_MAJOR	0
#define LIBDUSTBUNNY_VERSION_MINOR	2
#define LIBDUSTBUNNY_VERSION_PATCH	0

#define LIBDUSTBUNNY_RELEASE_YEAR	2026

#endif
